# GoRun Rust rewrite
[package]
name = "GoRun"
version = "1.0.0"
edition = "2021"
build = "build.rs"
windows_subsystem = "windows"

[build-dependencies]
slint-build = "1.7"

[features]
default = ["backend-winit"]
backend-winit = ["slint/backend-winit"]
backend-testing = ["slint/system-testing", "dep:i-slint-backend-testing"]

[dependencies]
slint = { version = "1.7", default-features = false, features = ["renderer-software", "compat-1-2"] }
i-slint-backend-testing = { version = "1.7", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
image = "0.25"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
chrono = "0.4"

[profile.release]
opt-level = 3
lto = true
